### ISSUE TITLE
tag include extend  have something examples?

### ISSUE THREAD

**Issue by wuchuguang** [erlydtl/erlydtl#226]
i use include ,extend tag have something like bug.
can provide examples?

**Comment by kaos** [comment]
The documentation for erlydtl is sparse, but most examples from the django documentation for their templating should apply equally here (when not, it is a bug, except for additional functionality from libraries etc).
https://docs.djangoproject.com/en/1.9/topics/templates/

Otherwise, for erlydtl examples, the test sources are the best examples.
https://github.com/erlydtl/erlydtl/tree/master/test/files/input
